### PR TITLE
Members page

### PR DESCRIPTION
**Pull request by szaghi**
Dear all,

I have added a _skeleton_ page for Members list. For few of us ( @jacobwilliams @cmacmackin @aamaricci ) I have added some data (please check for correctness) as an example of _layout_. In particular, I like to highlight our projects developed outside the group, but related to Fortran. I hope you agree.

If you like this layout, I can add in the future the data of all us, but very slow: I much prefer that each of us takes care of his/her own _placeholder_, but I can serve as _plane B_.

I hope to improve other pages soon.

My best regards.

### CODE REVIEW

**Comment by victorsndvg** [comment]
Good work @szaghi !

**Comment by zbeekman** [comment]
Looks Good to Me!

**Comment by szaghi** [comment]
Ok, I will wait for @cmacmackin and @jacobwilliams and @aamaricci approvals before merge this.

**Comment by aamaricci** [comment]
looks ok to me. Thanks Stefano!

Cheers,
A

**Comment by cmacmackin** [comment]
If you don't mind, could you remove `futility` from the list of my projects. I've never really developed it into anything useful. Other than that, looks good.

**Comment by szaghi** [comment]
@cmacmackin sure, no problem. I am waiting for @jacobwilliams modifications, then I will remove _futility_ (that, indeed, I like :smile: ).

@aamaricci thank you for your feedback.

**Comment by cmacmackin** [comment]
@szaghi I'm still quite pleased with the name, but most of the things I had thought I'd put in there have been done by other people already and likely better than I would do them.

**Comment by aamaricci** [comment]
@Chris: actually I like futility a lot. I thought many times that we should
somehow merge SciFortran and futility (and possibly the other collections
of Fortran routines) in a single larger project.
In my view rather than having many different and specific prjects, it would
be much more useful (but also much more work) to have a single large
package.  Anyway, it can be that my view is wrong or biased :-)
A

**Comment by cmacmackin** [comment]
@aamaricci I think having a single project incorporating many of the existing utilities and mathematical routines is a good idea. I would be happy for it to use the name `futility`. I just don't know that anything which I have in that repository at the moment is good enough to make the cut.

**Comment by szaghi** [comment]
@aamaricci @cmacmackin my dear, indeed I am here somehow not _streamlined_ with you: I prefer _thiny_ codes (library/app) tailored to few goals and doing those at their best rather huge collections aggregating not-so-related stuffs. This is not the case of SciFortran, that collects many _tiny_ goals but high-related to scientific computations as well Chris' _futility_ that is a little more general.

In general, I now prefer the KISS phylosophy, Keep It Simple and Stupid: this helps me to develop and maintain the _tiny_ codes.

Cheers.

**Comment by aamaricci** [comment]
Eheh. These are different strategies that work for different things.

I adopt a kiss philosophy for minor and more specific projects, but on the
other hand while coding (something that I started relatively late in my
life) I realized that fortran, even being very much scientific oriented
language, lacks of a serious, complete scientific framework.

I am thinking here at something like scipy/numpy for python, GSL for C and
so on.
Something the new or inexperienced user can use easily to perform basic
tasks. This will allow to focus better on more specific problems without
having to reinvent the wheel  every time.

Imagine that as you now use matmul rather than a nested do loop, tomorrow
you could use inv, eigh, etc... rather than a complicated call to lapack
routines.

This is what led me to organize some of the code I wrote or I found on-line
in SciFortran: 1 installation, 1 dependence, 1 library access to (almost)
all needed software.

Then much has to be done yet, but this is a first step.

Cheers
A

Il Sab 21 Mag 2016, 07:59 Stefano Zaghi notifications@github.com ha
scritto:

**Comment by jacobwilliams** [comment]
Looks good to me!

**Pull request merged**
